<?php
$_POST['statement']="dasdsa";
?><?php
$_POST['statement']="dasdsa";
?><?php
$_POST['statement']="test123";
?><?php
$_POST['statement']="asASSDSADDSAD";
?>
<?php
$_POST['statement']="kaushik";
?>
<?php
$_POST['statement']="I Love You";
?><?php
$_POST['statement']="asdf";
?>
<?php
$_POST['statement']="Abhishek Chinni";
?><?php
$_POST['statement']="Sai";
?><?php
$_POST['statement']="saipraneeth";
?><?php
$_POST['statement']="manikanta";
?><?php
$_POST['statement']="Sherlock";
?>
<?php
$_POST['statement']="saipraneeth";
?><?php
$_POST['statement']="hardhik";
?><?php
$_POST['statement']="asdasdas";
?><?php
$_POST['statement']="manoj";
?>
<?php
$_POST['statement']="asdf";
?><?php
$_POST['statement']="manikanta";
?><?php
$_POST['statement']="basina";
?><?php
$_POST['statement']="basina";
?><?php
$_POST['statement']="manikanta";
?><?php
$_POST['statement']="Kondeti";
?><?php
$_POST['statement']="phani";
?><?php
$_POST['statement']="aswq";
?><?php
$_POST['statement']="asdqwe";
?><?php
$_POST['statement']="fasdf";
?><?php
$_POST['statement']="fg";
?><?php
$_POST['statement']="lol";
?><?php
$_POST['statement']="dfs";
?><?php
$_POST['statement']="lol";
?><?php
$_POST['statement']="Ash";
?><?php
$_POST['statement']="jaffa";
?><?php
$_POST['statement']="MANOJ";
?><?php
$_POST['statement']="pakija";
?><?php
$_POST['statement']="fe";
?>
<?php
$_POST['statement']="fdfhdf";
?><?php
$_POST['statement']="sravya";
?><?php
$_POST['statement']="naina";
?><?php
$_POST['statement']="dasdsa";
?><?php
$_POST['statement']="huur";
?><?php
$_POST['statement']="priya";
?><?php
$_POST['statement']="mehar";
?>
<?php
$_POST['statement']="ninja";
?><?php
$_POST['statement']="Sindhu";
?><?php
$_POST['statement']="name";
?><?php
$_POST['statement']="Karan";
?><?php
$_POST['statement']="gfdg";
?><?php
$_POST['statement']="Ranganath";
?><?php
$_POST['statement']="pg";
?><?php
$_POST['statement']="chaitanya";
?>
<?php
$_POST['statement']="Arnav";
?><?php
$_POST['statement']="kunj";
?><?php
$_POST['statement']="iiojp";
?><?php
$_POST['statement']="sunil";
?><?php
$_POST['statement']="RAN";
?><?php
$_POST['statement']="ascasd";
?><?php
$_POST['statement']="basina";
?>
<?php
$_POST['statement']="dasdsa";
?><?php
$_POST['statement']="aayush";
?><?php
$_POST['statement']="fgygy";
?><?php
$_POST['statement']="diksha";
?><?php
$_POST['statement']="ravi teja";
?><?php
$_POST['statement']="dawfre";
?>
<?php
$_POST['statement']="201101044";
?><?php
$_POST['statement']="CCC";
?><?php
$_POST['statement']="dasdsa";
?><?php
$_POST['statement']="nee gudda";
?><?php
$_POST['statement']="sai";
?><?php
$_POST['statement']="rajat";
?><?php
$_POST['statement']="Trevor";
?><?php
$_POST['statement']="Akhil Varma";
?><?php
$_POST['statement']="Kondeti";
?>
<?php
$_POST['statement']="Akhil Varma";
?><?php
$_POST['statement']="samatha";
?>
<?php
$_POST['statement']="hello";
?><?php
$_POST['statement']="Happy";
?><?php
$_POST['statement']="APJ Abdul Kalam";
?><?php
$_POST['statement']="lyte";
?><?php
$_POST['statement']="du_UH";
?><?php
$_POST['statement']="a";
?><?php
$_POST['statement']="saifulla";
?><?php
$_POST['statement']="chandu";
?><?php
$_POST['statement']="sandeep";
?><?php
$_POST['statement']="Akhil Varma";
?><?php
$_POST['statement']="peter jackson";
?><?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="x";
?><?php
$_POST['statement']="x";
?><?php
$_POST['statement']="sdkajdl";
?><?php
$_POST['statement']="Vamshi";
?><?php
$_POST['statement']="asdf";
?><?php
$_POST['statement']="kkk";
?><?php
$_POST['statement']="Akhil Varma";
?><?php
$_POST['statement']="sundeep";
?><?php
$_POST['statement']="vader";
?><?php
$_POST['statement']="HEllo";
?><?php
$_POST['statement']="ABCD";
?><?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="ramoo";
?><?php
$_POST['statement']="hello";
?><?php
$_POST['statement']="Raveesh";
?><?php
$_POST['statement']="kansi";
?><?php
$_POST['statement']="Aman Sharma";
?><?php
$_POST['statement']="p";
?><?php
$_POST['statement']="Anubhav Gupta";
?><?php
$_POST['statement']="blah!";
?><?php
$_POST['statement']="adasd";
?><?php
$_POST['statement']="Akhil";
?><?php
$_POST['statement']="Prathyusha Danda";
?><?php
$_POST['statement']="Hello World";
?><?php
$_POST['statement']="Hello World";
?><?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="sd";
?><?php
$_POST['statement']="lol";
?><?php
$_POST['statement']="hola amigo";
?><?php
$_POST['statement']="hh";
?><?php
$_POST['statement']="abcd";
?><?php
$_POST['statement']="prashant";
?><?php
$_POST['statement']="asadsdgdszf";
?><?php
$_POST['statement']="Akhil Varma";
?><?php
$_POST['statement']="shantanu";
?><?php
$_POST['statement']="hhhh";
?><?php
$_POST['statement']="rocko";
?><?php
$_POST['statement']="balayya";
?><?php
$_POST['statement']="Manikanta";
?><?php
$_POST['statement']="Zuckerburg";
?><?php
$_POST['statement']="vennela";
?><?php
$_POST['statement']="gurshaant";
?><?php
$_POST['statement']="Tarang Goyal";
?><?php
$_POST['statement']="Hello";
?>
<?php
$_POST['statement']="test123";
?>
<?php
$_POST['statement']="rachana";
?><?php
$_POST['statement']="dfsd";
?>
<?php
$_POST['statement']="dfsd";
?>
<?php
$_POST['statement']="Prudhvi Penmethsa";
?><?php
$_POST['statement']="Akhil Varma";
?>
<?php
$_POST['statement']="Ass";
?><?php
$_POST['statement']="Dick";
?><?php
$_POST['statement']="gvk";
?><?php
$_POST['statement']="shadow";
?><?php
$_POST['statement']="why so!";
?><?php
$_POST['statement']="hello!";
?><?php
$_POST['statement']="!";
?><?php
$_POST['statement']="why!";
?><?php
$_POST['statement']="q";
?><?php
$_POST['statement']="k";
?><?php
$_POST['statement']="Saumya";
?><?php
$_POST['statement']="k";
?><?php
$_POST['statement']="yash";
?><?php
$_POST['statement']="abc";
?><?php
$_POST['statement']="lol";
?><?php
$_POST['statement']="hardhik";
?><?php
$_POST['statement']="sudhir is sudhir";
?><?php
$_POST['statement']="Daffa";
?><?php
$_POST['statement']="vamshi";
?><?php
$_POST['statement']="12";
?><?php
$_POST['statement']="*";
?><?php
$_POST['statement']="kj";
?><?php
$_POST['statement']="bhavana";
?><?php
$_POST['statement']="Nikhil";
?><?php
$_POST['statement']="ramyasri";
?><?php
$_POST['statement']="lauda";
?><?php
$_POST['statement']="rohit jain";
?><?php
$_POST['statement']="kbkbgkgkugk";
?><?php
$_POST['statement']="fuckoff";
?><?php
$_POST['statement']="meghesh";
?><?php
$_POST['statement']="Batman";
?><?php
$_POST['statement']="vinil";
?><?php
$_POST['statement']="narang";
?><?php
$_POST['statement']="Superman";
?><?php
$_POST['statement']="sudhanshu";
?><?php
$_POST['statement']="gyjjh";
?><?php
$_POST['statement']="Vamsi";
?><?php
$_POST['statement']="lanjamunda";
?><?php
$_POST['statement']="musti madda";
?><?php
$_POST['statement']="anirudh";
?><?php
$_POST['statement']="fuck";
?><?php
$_POST['statement']="meghesh";
?><?php
$_POST['statement']="a";
?><?php
$_POST['statement']="Akhil Varma";
?><?php
$_POST['statement']="Akhil Varma";
?><?php
$_POST['statement']="ramya";
?><?php
$_POST['statement']="Nik";
?><?php
$_POST['statement']="kaushik";
?><?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="Madhavan";
?><?php
$_POST['statement']="akhil";
?><?php
$_POST['statement']="manikondi_kondaaaaaaaaaaa";
?>
<?php
$_POST['statement']="dfsd";
?>
<?php
$_POST['statement']="vamshi";
?><?php
$_POST['statement']="satya";
?><?php
$_POST['statement']="vishnu";
?><?php
$_POST['statement']="sd";
?><?php
$_POST['statement']="blah";
?><?php
$_POST['statement']=";l";
?><?php
$_POST['statement']="goutham";
?><?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="satya";
?><?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="sdfds";
?>
<?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="asdqwe";
?><?php
$_POST['statement']="suck";
?><?php
$_POST['statement']="Rashika Kheria";
?>
<?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="asdf";
?><?php
$_POST['statement']="asdf";
?><?php
$_POST['statement']="Abhishek Chinni";
?>
<?php
$_POST['statement']="dfsd";
?>
<?php
$_POST['statement']="name";
?><?php
$_POST['statement']="dfsd";
?>
<?php
$_POST['statement']="dfsd";
?>
<?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="123";
?><?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="abhishek";
?><?php
$_POST['statement']=":P";
?><?php
$_POST['statement']="8";
?><?php
$_POST['statement']="Tiwari";
?><?php
$_POST['statement']="dfsd";
?>
<?php
$_POST['statement']="rishika";
?><?php
$_POST['statement']="Jasmine";
?>
<?php
$_POST['statement']="dfsd";
?><?php
$_POST['statement']="mani";
?><?php
$_POST['statement']="Deepak Goyal";
?><?php
$_POST['statement']="Ankita";
?><?php
$_POST['statement']="e3r5gebd";
?><?php
$_POST['statement']="mani";
?><?php
$_POST['statement']="mani";
?><?php
$_POST['statement']="mani";
?>
<?php
$_POST['statement']="Anuraag";
?><?php
$_POST['statement']="krishna";
?><?php
$_POST['statement']="Abhishek Chinni";
?><?php
$_POST['statement']="kiko";
?>
<?php
$_POST['statement']="achintye";
?><?php
$_POST['statement']="xyz";
?><?php
$_POST['statement']="manikanta";
?><?php
$_POST['statement']="mani";
?>
<?php
$_POST['statement']="mani";
?>
<?php
$_POST['statement']="mani";
?>
